### ISSUE TITLE
Using root in the same directory as libremollroot.so causes problems

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#105]
Running root in the directory with libremollroot.so returns these errors:

`dlopen error: /share/apps/geant4/geant4.10.01.p03-install/lib64/libG4particles.so: cannot allocate memory in static TLS block
Load Error: Failed to load Dynamic link library /home/cameronc/gitdir/remoll/build/./libremoll.so
Warning: Return value of void rootlogon() ignored rootlogon.C:4:
root [0]
Attaching file remoll_merged_1M.root as _file0...
dlopen error: /share/apps/geant4/geant4.10.01.p03-install/lib64/libG4particles.so: cannot allocate memory in static TLS block
Load Error: Failed to load Dynamic link library /share/apps/root/lib/libThread.so
Error in <TCint::AutoLoadCallback>: failure loading dependent library libThread.so for class TFile
dlopen error: /share/apps/geant4/geant4.10.01.p03-install/lib64/libG4particles.so: cannot allocate memory in static TLS block
Load Error: Failed to load Dynamic link library /share/apps/root/lib/libRIO.so
Error in <TCint::AutoLoadCallback>: failure loading library libRIO.so for class TFile
Error: Function Open("remoll_merged_1M.root") is not defined in current scope  (tmpfile):1:
*** Interpreter error recovered ***`

**Comment by cameronc137** [comment]
Possibly related, opening a remoll output file in a folder not containing the libremollroot.so file complains:

`Attaching file remoll_merged_1M.root as _file0...
Warning in <TClass::TClass>: no dictionary for class remollUnits_t is available
Warning in <TClass::TClass>: no dictionary for class remollEvent_t is available
Warning in <TClass::TClass>: no dictionary for class remollBeamTarget_t is available
Warning in <TClass::TClass>: no dictionary for class remollEventParticle_t is available
Warning in <TClass::TClass>: no dictionary for class remollGenericDetectorHit_t is available
Warning in <TClass::TClass>: no dictionary for class remollGenericDetectorSum_t is available
Warning in <TClass::TClass>: no dictionary for class remollRunData is available
Warning in <TClass::TClass>: no dictionary for class remollTextFile is available
Warning in <TClass::TClass>: no dictionary for class filedata_t is available`

**Comment by wdconinc** [comment]
I am just going to remove `rootlogon.C`. It's a bandaid approach that leads to unpredictable and usually incorrect behavior. Use `reroot` or LD_PRELOAD. I will write docs for that, part of README.
