### ISSUE TITLE
Energy and momentum units are in MeV instead of GeV as in prior versions

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#106]
I can't find the line where the units are being converted from GeV (beam energy set in the remollglobs.hh file, or in a macro command), but I do know that the output root tree is reporting things with momenta 1000 X higher than they should be.

https://github.com/JeffersonLab/remoll/blob/9f17ed7e719a6a15270b73d88e95d6a35c4c53d7/variables.txt#L45

**Comment by wdconinc** [comment]
Energy units in the ROOT file are now equal to energy units in Geant4. This greatly simplifies the IO and avoids any kind of discussion. Suggested use:
```
T->Draw("hit.p/GeV")
```

I will update variable.txt to reflect this. Thanks for catching this.

I think only W^2 and Q^2 may still be stored in GeV so I'll modify those while I'm at it.

**Comment by wdconinc** [comment]
So, to answer your specific issue: there is no line where the energy units are being converted.

**Comment by wdconinc** [comment]
Incidentally, also distances are stored in mm, no m.

**Comment by cameronc137** [comment]
Where were the lines in the code that made the simulation default to GeV and m in the previous version?

**Comment by wdconinc** [comment]
There used to be a long list of `/__E_UNIT` lines in remollIO.cc. Every time you added something to a hit, you also had to go in and (if you remembered) divide by __E_UNIT there. It won't surprise anyone that reality had diverged from that intention substantially.
