### ISSUE TITLE
Proposal to remove fCollCut from output file

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#107]
It's an event-level quantity that relies on hard-coded interpretation of detector IDs which may not be correct anymore anyway. As far as I know, no one uses it. Waiting for affirmative approval to remove from @cameronc137 @rakithab @cipriangal

**Comment by cameronc137** [comment]
I don't use it, so that's fine for me.

**Comment by cipriangal** [comment]
i'm fine with taking it out but maybe Rakitha would care.
