### ISSUE TITLE
Optical photon detector problems

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#113]
Using the /remoll/physlist/optical/enable macro command allows optical photons to exist, but it does not allow optical photons to be detected with the "opticalphoton" aux type sensitive detector without actually hardcoding these optical and low energy neutral cuts to true.

https://github.com/JeffersonLab/remoll/blob/03baf7b35b2e55840793f1dc4561232aa83f0a29/src/remollGenericDetector.cc#L22

**Comment by wdconinc** [comment]
It should. I get optical photons stored with the test case in macros/tests/unit/. Here is where the GDML is read: https://github.com/JeffersonLab/remoll/blob/03baf7b35b2e55840793f1dc4561232aa83f0a29/src/remollDetectorConstruction.cc#L437

**Comment by wdconinc** [comment]
I don't think planeDet is used. Originally was intended for different types of detectors that inherit from GenericDetector. Never implemented.

**Comment by cameronc137** [comment]
Oh, I see. I was looking directly at the plane detector 28, but yes, I do see them hitting the pion detector.

**Comment by cameronc137** [comment]
Oh dear. That's not true. I had those two optical photon and low energy neutral things set to true, and then recompiling with them set to false turns off the optical photon storing, even in the pion detectors.

**Comment by acfarrell** [comment]
Looking at Issue #21 I see that this is likely a Geant4 version issue. Our local computer is running 10.03. We'll try updating to 10.04 tomorrow to see if that resolves the issue. This would explain a lot of our problems related to optical physics with the GDML detectors.
