### ISSUE TITLE
Some more unit issues

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#115]
Looking at root output it appears that the part.v[xyz] variables are actually in mm instead of meters. It also appears that the claim of ev.thcom being in degrees is actually in radians rather than degrees.

One other issue is that the conversion of each branch in the output root tree to have the default geant4 units may not have worked for all of the branches. Specifically, when running analysis on some branches, using the rootlogon.C linked dictionaries (see https://github.com/sbujlab/rad_analysis/blob/master/rootlogon.C and remolltypes.hh and the Makefile and its analysis codes in that repository for an example), we get errors when looking at the hit sums (specifically for E deposited), about not being able to find the right struct for remollUnits_t in the remoltypes.hh file, event though they were there. So I guess the hit Sums still have the remoll specific units rather than the recently restored Geant4 defaults.

https://github.com/JeffersonLab/remoll/blob/9950890ff97802f2d4647cecd5fb7a386ff9682c/variables.txt#L23

**Comment by wdconinc** [comment]
https://github.com/JeffersonLab/remoll/blob/develop/variables.txt, not the one in master.

**Comment by wdconinc** [comment]
There 8fec69d506050a469899084b7aad799f885cf5e1. Now each time you want to submit a bug report there's a helpful template :-) Of course, this is useful for everyone. Back to this bug at hand now.

Edep should be in geant4 internal units too (MeV). Are you saying it isn't?

**Comment by cameronc137** [comment]
Looking into the histograms and comparing the kinds and integrals of energy stored, yes, sum.edep, hit.edep, and hit.e do appear to have the same units.

Also, we took the new readme steps from the #105 fix and that successfully finds the units. So the problem with missing remollUnits_t definitions has been fixed on my end.

Thanks!
