### ISSUE TITLE
Optical photon hit positions stored as prestep point inside previous volume

### ISSUE THREAD

**Issue by acfarrell** [JeffersonLab/remoll#127]
### Environment: (where does this bug occur, have you tried other environments)
- Branch: bugfix-opticalProperties
- revision (HEAD for most recent): HEAD
- OS or system: CentOS 6.9
- Special ROOT or Geant4 versions? Geant4.10.04, ROOT 5.34/36, GCC 4.9.2

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1.  ./build/remoll macros/optics_test.mac
2.  root remollout_photons.root
3.  T->Draw("hit.y:hit.x","hit.det == 50402") 
4.  root remollout_quartz.root
5.  T->Draw("hit.y:hit.x","hit.det == 50402")

### Expected Result: (what do you expect when you execute the steps above)
The photon plot in step 3 should show around 30% of the total photons shot on the cathode. The quartz plot from step 5 should show around 33 photons hitting the cathode. The cathode itself is a disk with a diameter of approximately 80mm, positioned near x=-1315, and so we expect all hits to fall within this volume. 

### Actual Result: (what do you get when you execute the steps above)
For the photon plot in Step 3, we see that the cathode is recording the expected number of hits (around 30% of the photons, defined by the efficiency matrix in matrices_mainz.mac), but the position being recorded is the point where the generator produced the particle as defined in the macro commands. Moving the origin position in the macro moves the hit position to exactly match, even though these hit positions are outside the cathode volume to which the sensitive detector is defined. 

For the quartz plot in step 5, we see what seems to be photons hitting the sides of the light guide after having been reflected off of the cathode. The number of hits is what we'd expect but the positions are again outside the cathode volume. We have verified that the cathode detector (no. 50402) is not multiply defined.

**Comment by wdconinc** [comment]
Also, I found it quite convenient to use the following command to test:
```
root -l remollout_photons.root -e 'T->Draw("hit.y:hit.x","hit.det == 50402")'
```
Does the testing all in one step :-)

**Comment by wdconinc** [comment]
Second part of the simulation (quartz) now returns hits like this:
![image](https://user-images.githubusercontent.com/4656391/43359631-7003dde6-9273-11e8-9dc6-a3d8653801d9.png)

**Comment by wdconinc** [comment]
(for 1000 events) 

I don't think that "the quartz plot from step 5 should show around 33 photons hitting the cathode" since all of the 1000 electrons at 855 MeV will generate many Cerenkov photons. So there's a multiplication of optical photons before we have to think about the 33% efficiency

**Comment by cameronc137** [comment]
For the "33 photons hitting the cathode" I think that is referring to the expected Photo-Electron yield. From prior qsim and beam tests we saw that the geometry in question yielded ~33 photoelectrons in the pmt per electron on Quartz, and the counting here generally matches that, which is good. 

Thanks for finding the problem! We will use this fix and check that it works (and we can cross check with other geometries that were also benchmarked in the past to make sure the optical physics respond to those changes and the agreement so far wasn't a coincidence)
