### ISSUE TITLE
Proposed branch deletion: dose

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#129]
Now that dose has been merged into develop (through an integration branch), we can delete it. All dose commit history is now subsumed in develop. Waiting for approval from others first.

**Comment by wdconinc** [comment]
@rakithab @cameronc137

**Comment by wdconinc** [comment]
The only valid reason for keeping the dose branch around, I think, is if you have active work that is referenced against that branch. Any new work would probably benefit from branching off anew from develop or master. But I may be overlooking something.

Also tagging @cipriangal

**Comment by cameronc137** [comment]
My geometry modifications are on a dose-forked branch in the sbujlab repo (begun before I had JLab push privileges). Probably those commits can be cherry picked into a develop fork. There are some non-geometry changes I had made there too, but they should not be included into develop. Should I go through my geometry commits and pick the ones to pull into develop?

**Comment by wdconinc** [comment]
You could try a rebate against develop now and see how much is left to merge into develop.

**Comment by wdconinc** [comment]
*rebase

**Comment by cameronc137** [comment]
Because the important stuff in dose was all successfully merged into develop and I have placed all of the history that could be interesting for back-tracking geometry updates into cameron_dose_branch I would say that yes, dose branch is not needed for geometry-tracking purposes anymore.

**Comment by cipriangal** [comment]
I have not been doing any work with the dose branch so from my side I am happy with it's deletion.
