### ISSUE TITLE
No-field map graceful (and helpful failure)

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#161]
**Is your feature request related to a problem? Please describe.**
When I pull a new copy of the directory I always forget about the field map files, and when I run remoll with a macro that assumes a map_directory (whatever name it may have in whichever macro) it segfaults and fails without much to point me in the direction of the problem (the last thing pre-segfault is usually the map reading, and I remember it now)

**Describe the solution you'd like**
but for a new person it may be nice to have a warning (with the url to the suggested field maps) and clean exit when a macro command reads a map file and can't find it.

**Describe alternatives you've considered**
Some convoluted way of recursively searching for files nearby with the right field map extension would be cool, but overly complicated.

**Comment by cameronc137** [comment]
A handy script that makes the map folder and wget's the map files would be nice actually.

**Comment by wdconinc** [comment]
cmake could actually do this as a build target. It would fail compilation if you try to build without internet connection, though, unless you trick it into thinking the file is there already. It would also violate out of source build philosophy

**Comment by cameronc137** [comment]
Resolved in https://github.com/JeffersonLab/remoll/commit/140f4638707fb7e68e650d1539124c351829fb2a

**Comment by wdconinc** [comment]
Added cmake target that downloads the field maps in 2e0012d..c12ccd7  feature-cmake-analysis-in-subproject
