### ISSUE TITLE
Who is still using ROOT 5.34? Should we keep supporting old ROOT versions?

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#165]
Please post below some good reasons why we should keep supporting ROOT 5.34.

Bad reasons are:
- I don't have a computer with ROOT 6 (ifarm has ROOT 6 in /site/12gev_phys/2.0 through 2.3)
- ROOT 5.34 has a feature that is not available and that I absolutely need (you should have a plan in place to not depend on ROOT 5.34 in the near future)

**Comment by wdconinc** [comment]
@rakithab @cameronc137 @cipriangal @mcnudust 

The debugging of issues is really hard if I have no system with ROOT 5.34 on it (it's even difficult to use it on ifarm). I don't want to cut someone off from working on physics, but it's becoming disproportionally a sink on debugging time...

**Comment by cameronc137** [comment]
Hello,

I have updated the SBU JLab group's cluster (mocha) to also have ROOT 6.14
today, so this will no longer be a problem for us (and if someone at SBU
has issues with the new ROOT version please let me know).

Thanks,
Cameron Clarke

**Comment by cipriangal** [comment]
I use r6.12 so I am fine with losing support for r5.34.
