### ISSUE TITLE
Sum variables behave strangely

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#167]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD
- OS or system: Cenos 6.9
- Special ROOT or Geant4 versions? newest of both

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Standard build, use macros/runexample.mac (and add more events if you want better resolution on the problems)
2. Execute T->Draw() commands on the output files:
3. ```T->Draw("sum.by_pid.edep>>h2","sum.by_pid.edep*(sum.by_pid.pid==22 && sum.det==2002)")```; and then integrate with ```h2->Integral()```
4. ```T->Draw("sum.edep>>h3","sum.edep*(sum.pid==22 && sum.det==2002)")```; and then integrate with ```h3->Integral()```

For 10k events I get these plots: 
![image](https://user-images.githubusercontent.com/12798552/49032130-d152c700-f179-11e8-99a6-24ae2f44ea71.png)
and integral = 18.07 (I've weighted the output by Watts/85 uA)
and
![image](https://user-images.githubusercontent.com/12798552/49032215-0b23cd80-f17a-11e8-9b0c-ff5ea804f0e3.png)
with integral 10131.38 (same weighting)

### Expected Result: (what do you expect when you execute the steps above)
I would expect for the output plots and integral to be the same from these two scenarios

### Actual Result: (what do you get when you execute the steps above)
But instead I get a much smaller result from the sum.by_pid.* case. I realize that there is no sum.pid variable, and so it is likely that the sum.pid cut request actually looks inside the by_pid leaves and returns the value of sum.edep per each sub-entry (artificially overcounting the edep).

Why does ROOT allow me to use sum.pid even though it doesn't exist as a variable? Can we assume that the data produced before this sum.by_pid.* structure was included accurately mapped the sum.pid information to the sum.edep (since we need to compare old energy deposition simulation results to new ones made with these two versions of the sum.* structures)?

I have made a stab at doing a separate pid-wise sum branch, intended to mimic the sum.edep but with a corresponding sum.pid variable that allows for separating out the results for different pids, in branch feature-pid-sums, but I am not convinced that I have done it correctly or added anything new that wasn't already contained in the by_pid leaves.

**Comment by wdconinc** [comment]
This may make the structure clearer:
```
T->Scan("@sum.size():sum.det:sum.edep:sum.@by_pid.size():sum.by_pid.edep:sum.by_pid.pid:sum.by_pid.z")
```
i.e.
```
re-root [11]  T->Scan("@sum.size():sum.det:sum.edep:sum.@by_pid.size():sum.by_pid.edep:sum.by_pid.pid:sum.by_pid.z")
***********************************************************************************************************
*    Row   * Instance * @sum.size *   sum.det *  sum.edep * sum.@by_p * sum.by_pi * sum.by_pi * sum.by_pi *
***********************************************************************************************************
*        0 *        0 *         1 *      2001 * 10.101991 *        17 * 1.4862599 *        11 *  5275.005 *
*        0 *        1 *         1 *           *           *           * 0.2789357 *       -11 * 5275.7316 *
*        0 *        2 *         1 *           *           *           * 0.0075737 *       -11 * 5302.4911 *
*        0 *        3 *         1 *           *           *           * 0.3685895 *       -11 * 5304.0373 *
*        0 *        4 *         1 *           *           *           * 0.2455876 *        11 * 5304.0373 *
*        0 *        5 *         1 *           *           *           *  0.069689 *        22 * 5304.0939 *
*        0 *        6 *         1 *           *           *           * 0.0011899 *        11 * 5304.2069 *
*        0 *        7 *         1 *           *           *           * 1.4006306 *        11 * 5302.4911 *
*        0 *        8 *         1 *           *           *           * 0.5698178 *        11 * 5275.7316 *
*        0 *        9 *         1 *           *           *           * 0.0209422 *       -11 * 5277.1724 *
*        0 *       10 *         1 *           *           *           * 0.0011261 *        11 * 5277.4346 *
*        0 *       11 *         1 *           *           *           * 1.7897862 *        11 * 5277.1724 *
*        0 *       12 *         1 *           *           *           * 0.1754734 *       -11 * 5280.8873 *
*        0 *       13 *         1 *           *           *           * 0.1759572 *       -11 * 5322.3323 *
*        0 *       14 *         1 *           *           *           * 3.1133871 *        11 * 5322.3323 *
*        0 *       15 *         1 *           *           *           * 0.1335002 *        11 * 5280.8873 *
*        0 *       16 *         1 *           *           *           * 0.2635451 *        11 * 5283.1305 *
*        1 *        0 *         3 *      2001 * 5.5757399 *        11 * 0.0299591 *        11 *  5275.005 *
*        1 *        1 *         3 *      2002 * 18.228852 *        40 * 1.0813130 *       -11 * 5285.5595 *
*        1 *        2 *         3 *      6010 * 58.941804 *        60 * 0.0860379 *       -11 * 5292.4082 *
*        1 *        3 *         3 *           *           *           * 1.5505523 *        11 * 5292.4082 *
*        1 *        4 *         3 *           *           *           * 0.4955874 *        11 * 5285.5595 *
*        1 *        5 *         3 *           *           *           * 0.4117550 *       -11 * 5293.9993 *
*        1 *        6 *         3 *           *           *           * 1.6601666 *        11 * 5293.9993 *
*        1 *        7 *         3 *           *           *           *  0.069689 *        22 * 5294.1692 *
Type <CR> to continue or q to quit ==>
```

This isn't really meant to be useful when using T->Draw() statements (which are inherently limiting). As you can tell for the second event, row 1, you can use sum.det == 2002 to select the hits in that detector and then sum.by_pid.pid == 11 to select the hits in that detector with PID == 11. Theoretically, and probably not reliably so in a T->Draw() statement.

**Comment by wdconinc** [comment]
Now, I'm not sure what you are trying to get to with the integral of sum.edep weighted with sum.edep. But sum.pid is likely ill-defined (ROOT tends to fall through until it recognizes a leaf name, hence why the use of units lik cm works anywhere even though they are in the units branch).

**Comment by wdconinc** [comment]
Looking at your integrals, these give me the output (with Scan lines inserted):
```
Processing test_issue167.C...
***********************************************************
*    Row   * Instance * sum.by_pi * sum.by_pi *   sum.det *
***********************************************************
*        1 *       12 *  0.012077 *        22 *      2002 *
*        1 *       16 *  0.069689 *        22 *      2002 *
*        1 *       20 *  0.010206 *        22 *      2002 *
*        1 *       27 *  0.069689 *        22 *      2002 *
*        1 *       31 *  0.069689 *        22 *      2002 *
*        1 *       35 *  0.069689 *        22 *      2002 *
*        1 *       37 *  0.069689 *        22 *      2002 *
*        1 *       40 *  0.069689 *        22 *      2002 *
*        1 *       46 *  0.069689 *        22 *      2002 *
*        2 *       26 *  0.069689 *        22 *      2002 *
*        2 *       30 *  0.011573 *        22 *      2002 *
*        3 *       16 *  0.069689 *        22 *      2002 *
*        3 *       22 *  0.069689 *        22 *      2002 *
*        6 *        2 *  0.069689 *        22 *      2002 *
*        6 *        7 *  0.012077 *        22 *      2002 *
*        6 *       10 *  0.069689 *        22 *      2002 *
*        8 *        3 *  0.069689 *        22 *      2002 *
***********************************************************
==> 17 selected entries
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
193.924
***********************************************************
*    Row   * Instance *  sum.edep *   sum.pid *   sum.det *
***********************************************************
*        1 *       12 * 18.228852 *        22 *      2002 *
*        1 *       16 * 18.228852 *        22 *      2002 *
*        1 *       20 * 18.228852 *        22 *      2002 *
*        1 *       27 * 18.228852 *        22 *      2002 *
*        1 *       31 * 18.228852 *        22 *      2002 *
*        1 *       35 * 18.228852 *        22 *      2002 *
*        1 *       37 * 18.228852 *        22 *      2002 *
*        1 *       40 * 18.228852 *        22 *      2002 *
*        1 *       46 * 18.228852 *        22 *      2002 *
*        2 *       26 * 6.3000009 *        22 *      2002 *
*        2 *       30 * 6.3000009 *        22 *      2002 *
*        3 *       16 * 3.5958119 *        22 *      2002 *
*        3 *       22 * 3.5958119 *        22 *      2002 *
*        6 *        2 * 4.9764953 *        22 *      2002 *
*        6 *        7 * 4.9764953 *        22 *      2002 *
*        6 *       10 * 4.9764953 *        22 *      2002 *
*        8 *        3 * 1.5417459 *        22 *      2002 *
***********************************************************
==> 17 selected entries
```
so you see that in the second case it keeps using sum.edep multiple times for each sum.by_pid entry.

**Comment by cameronc137** [comment]
I see, this makes a lot of sense, and thanks for the Scan examples (I wasn't aware you could do the @.size() call).

The integral of sum.edep weighted by sum.edep is so I can just integrate the histogram made by the draw command and find the total energy deposited in the detector with those cuts. This is mostly a quick and dirty way of accomplishing what is already being done in more detailed scripts by @chandabindu 

If instead of using root Draw() commands you just loop through (as Chandan is doing) the sum.by_pid.edep variable and sum it yourself using the sum.by_pid.pid and det variables to sort then you should be able to get a nice total energy deposited by a given pid in a given detector right? The behavior of these variables at least should work that way and any deviations from expected results may have to do with physics lists or geometry issues instead?

**Comment by wdconinc** [comment]
@cameronc137 Is this now a duplicate of #179? If so, please close. It's too vague here to find a solution.

**Comment by cameronc137** [comment]
Yes, #179 better describes what I was aiming for here. This issue did clear up some little confusions about ROOT tree behavior though, which is nice.
