### ISSUE TITLE
Code does not compile on G4.10.01.p01

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/remoll#18]
Looking at:
https://github.com/JeffersonLab/remoll/blob/master/src/remollOpticalPhysics.cc#L87

It seems to me that if I have an earlier version of G4 this code won't compile.

**Comment by wdconinc** [comment]
Just delete it :-) Remoll optical physics does not add anything over G4OpticalPhysics. I've done that in the pain branch.

**Comment by wdconinc** [comment]
But aParticleGenerator is a parent class variable, or at least theParticleGenerator is.

**Comment by cipriangal** [comment]
The error was aParticleGenerator was not declared .. which my guess is that since I don't have G4 version larger than 1030 the code at line 87 just doesn't run. 

Is aParticleGenerator declared somewhere else? Should aParticleGenerator variables below that line be replaced with "theParticleGenerator" ?

**Comment by cipriangal** [comment]
Might have been a problem with a previous build directory. Clearing it and recompiling doesn't produce the error.
