### ISSUE TITLE
Code fails to compile master on gitinfo error

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/remoll#19]
Checking out a fresh copy of master and trying to compile for the first time hangs up on:
[ 69%] Building CXX object CMakeFiles/remoll.dir/src/remollRunData.cc.o
/home/ciprian/playtime/remoll/src/remollRunData.cc:2:22: fatal error: gitinfo.hh: No such file or directory
 #include "gitinfo.hh"
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/remoll.dir/src/remollRunData.cc.o] Error 1
make[1]: *** [CMakeFiles/remoll.dir/all] Error 2
make: *** [all] Error 2
[ciprian@negoiu build]$ grep gitinfo ../src/*
../src/remollRunData.cc:#include "gitinfo.hh"

My guess this is related to this commit:
https://github.com/JeffersonLab/remoll/commit/86193634a3c8639651649a76191770f55279c705#diff-52845aab4628b4fe1c66538ffd1ddb39

**Comment by wdconinc** [comment]
Run make inside build at least the first time, I think. After that make -C build should work. It's more related to cmake not finding the pullgitinfo python script.

**Comment by wdconinc** [comment]
Pullgitinfo will create gitinfo.hh in build/include.

**Comment by cipriangal** [comment]
Series of commands to replicate:
 git clone https://github.com/JeffersonLab/remoll
 cd remoll/;mkdir build;cd build
 cmake ../
 make

running make produces the error above. running it again gives the same result. What am I missing?

**Comment by cipriangal** [comment]
if I 
 make gitinfo
and then make the rest it works fine.

I guess a modification to CMakeList to make sure gitinfo gets made first will fix this?

**Comment by wdconinc** [comment]
What about this patch to CMakeLists.txt? https://gist.github.com/wdconinc/8c288ac15c4b4a460872c23fce496414

I can't reliably reproduce the problem (CMake version, dependency resolution, probably some difference with your setup).

**Comment by cipriangal** [comment]
You should be able to reproduce this on ifarm1401 (cmake 3.5.1). I also see it on my Mac (older cmake) and on a RHEL 7.2 desktop configured by JLab.

The problem seems to be that on the first make it tries to make either remoll or remollout (interestingly the compiler on RHEL GNU 4.8.5 and the one on the ifarm node GNU 5.2.0 try to make remoll and remollout first respectively). 

What I found was to make gitinfo a dependency to the other executables/libs:
https://gist.github.com/cipriangal/08d9ccd8003949a883ab721f635d9f69

Your option also seems to do the job. I leave it up to you how you want to handle this. Thanks for looking into it.

**Comment by wdconinc** [comment]
Still can't reproduce on ifarm1401:
```
$ cmake --version
cmake version 2.8.11
$ which cmake
/usr/bin/cmake
```

Which cmake 3.5.1 are you using?

But if add_dependencies works, let's go with that. I can't verify so I don't want to commit it.

Technically gitinfo is not a dependency of of remoll or remollroot, but a dependency of src/remollRunData.cc. That means that even with add_dependency it could order the compiles such that gitinfo is only created after it attempts to compile src/remollRunData.cc. Another solution could be to use set_source_files_properties(src/remollRunData.cc OBJECT_DEPENDS gitinfo) but I couldn't get that to work. By using add_custom_command with an explicit OUTPUT the dependency resolution in cmake should properly resolve the dependency chain by the include of gitinfo.hh in src/remollRunData.cc.

**Comment by seamusriordan** [comment]
Did this get resolved?  "add_custom_command with an explicit OUTPUT the dependency resolution in cmake should properly resolve the dependency chain by the include of gitinfo.hh in src/remollRunData.cc"  sounded promising but does it need to be implemented and tested by someone?

**Comment by cipriangal** [comment]
I'll fix it first thing tomorrow. I tested that either method works (will probably implement Wouter's suggestion).

**Comment by wdconinc** [comment]
Yeah, I just ran into this again on the pion branch today. So, that's one system where I CAN reproduce it.

**Comment by cipriangal** [comment]
Implemented @wdconinc's suggestion: https://github.com/JeffersonLab/remoll/commit/8d9d226b6e062d03688e276968cf1062b5f2b21a

To reproduce it on the ifarm the env was:
 > Common Environment Version: <2.0>  (Wed Oct 6 2016)
 > Running as ciprian on ifarm1401.jlab.org
 > OS Release:    Linux_CentOS7.2.1511-x86_64-gcc5.2.0
 > JLAB_ROOT set to:     /site/12gev_phys
 > JLAB_SOFTWARE set to: /site/12gev_phys/2.0/Linux_CentOS7.2.1511-x86_64-gcc5.2.0

 > CLHEP    version: 2.3.3.1
 > XERCES   version: 3.1.3
 > QTDIR    version: 5.6.0
 > Geant4   version: 4.10.02.p02
 > ROOT     version: 6.08.00
 > GEMC     version: 2.5
 > JANA     version: 0.7.4p2
 > S Build  version: 1.4
 > EVIO     version: 5.1
 > CCDB     version: 1.06
 > Banks    version: 1.3
 > MLIBRARY version: 1.0

ifarm1401.jlab.org> cmake --version
cmake version 3.5.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
ifarm1401.jlab.org> which cmake
cmake: 	 aliased to /apps/cmake/bin/cmake

Note that indeed I have been using a different installation of cmake than the one mentioned above by @wdconinc
