### ISSUE TITLE
Feature Verification: Raster-position correlation implementation in beam target class

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#190]
**Is your feature request related to a problem? Please describe.**
The beam target class in develop has several macro commands that allow "old" and "new" raster use, as well as setting a correlation parameter between raster position and the angle that should correspond to the post-beamline-optics modification to the trajectory of rastered beam. Currently this is implemented, but with such terms as "theta" and "phi", though what coordinate system these angles are w.r.t. is not immediately clear, and whether or not it works as is should is also not clear.

**Describe the solution you'd like**
It would be nice to test the behavior and update the variable names to be clear and concise. It would also be nice to get the exact correlation parameters that will ultimately be used in the experiment hard coded as defaults in this class and to have the correct version of the raster (new?) set as the default as well.

**Describe alternatives you've considered**
Using the beam target methods seems to be the best way to go (rather than hard coding a raster into each generator), but we should remember that the "beam" generator does not utilize the beam target objects, so if people want to use genBeam to do physics quality simulations then these raster methods will need to be implemented in there as well (rudimentary raster has been added, but this correlation business has been neglected). 

**Additional context**
See: 
[HallA_11GeV_Moller.pdf](https://github.com/JeffersonLab/remoll/files/2815232/HallA_11GeV_Moller.pdf)

**Comment by cameronc137** [comment]
Of particular interest is the application of raster position/angle correlations to the production of envelopes. The envelopes we have made in the MOLLER CAD used the runexample_envelope.mac set of macros, and specifically in [line 18 of this one](https://github.com/JeffersonLab/remoll/blob/6a95473b9d86d85bd397512afc1a7eaa9a0b1bb2/macros/runexample_limit_envelope.mac#L18) we set "oldRas false", which means that [line 491 of the beam target class](https://github.com/JeffersonLab/remoll/blob/6a95473b9d86d85bd397512afc1a7eaa9a0b1bb2/src/remollBeamTarget.cc#L491) is being called - which appears to not have any angle correlation. We should fix the "oldras" method to do what we think it should (and probably change the name too), and decide on the position/angle correlation slopes (and offsets?).

**Comment by cameronc137** [comment]
This issue is clouded a bit by the description of the "oldras" macro command in [line 67 of the beam target class](https://github.com/JeffersonLab/remoll/blob/6a95473b9d86d85bd397512afc1a7eaa9a0b1bb2/src/remollBeamTarget.cc#L67) where it appears (to my eye at least) to contradict what is actually happening around line 491: https://github.com/JeffersonLab/remoll/blob/6a95473b9d86d85bd397512afc1a7eaa9a0b1bb2/src/remollBeamTarget.cc#L491

**Comment by wdconinc** [comment]
Currently in feature-gen-beam-correlated-raster as branched from develop.

![image](https://user-images.githubusercontent.com/4656391/53061147-e1352b00-348a-11e9-9fc0-e3f3f3b6d873.png)

![image](https://user-images.githubusercontent.com/4656391/53061192-0aee5200-348b-11e9-9c69-6b7585ab3e6c.png)

![image](https://user-images.githubusercontent.com/4656391/53061202-1772aa80-348b-11e9-8814-50b02eca1687.png)

**Comment by wdconinc** [comment]
After some more discussion with @rahmans1 it turns out that more is needed for this implementation to be useful. Instead of having the raster be the specified values at the z = -5 m, it makes more sense to have it be the specified values at z = 0, center of the target. That's implemented in f8990c6337c6262f6fed4d34ff8b325ca217476c with the following plots as outcome, starting from the test case
```
/run/initialize
/remoll/evgen/set beam    
/remoll/evgen/beam/origin 0 0 -5 m
/remoll/evgen/beam/direction 0 0 1
/remoll/evgen/beam/rasx 8 mm
/remoll/evgen/beam/rasy 5 mm
# units of correlation in mrad/mm
/remoll/evgen/beam/corrx 5
/remoll/evgen/beam/corry 1
/run/beamOn 1000
```

Beam parameters at z = 0:
a) x:y: raster indeed 8 mm x 5 mm
b) px:py: some angular range of 40 and 5 mrad.
c) x:px: correlation slope of 5 mrad / mm (4 mm turns into 20 mrad)
d) y:py: correlation slope of 1 mrad / mm (2.5 mm turns into 2.5 mrad
![raster_correlation_z0](https://user-images.githubusercontent.com/4656391/53117923-fd33dd80-3519-11e9-950b-abb3f82d6af5.png)

Beam parameters at z = -5 m (where tracks are generated):
same panels, but different extents, correlations, etc. Only px:py is the same since that isn't affected by linear projection.
![raster_correlation_zg](https://user-images.githubusercontent.com/4656391/53117925-fd33dd80-3519-11e9-8a60-51be2fc0d188.png)

**Comment by wdconinc** [comment]
Now all we need is some sensible default values here, then port this into the other generators (remollBeamTarget as well, hopefully by pulling this out here and reusing the code, but that's a project for v2.2).

**Comment by wdconinc** [comment]
From Figure 17 in https://github.com/JeffersonLab/remoll/files/2815232/HallA_11GeV_Moller.pdf linked above, we can deduce that 5 mm raster originate starting 15.075 m before the pivot at 150 m. That is a sensitivity of 0.165 mrad / 2.5 mm or 66.3 urad / mm. Probably we should therefore change the default settings to what we would get with the following:
```
/remoll/evgen/beam/origin 0 0 -15.075 m
/remoll/evgen/beam/rasx 5 mm
/remoll/evgen/beam/rasy 5 mm
/remoll/evgen/beam/corrx 0.0663 # mrad / mm
/remoll/evgen/beam/corry 0.0663 # mrad / mm
```
This would get the beam to a point source at -15.075 m upstream of the target and project a 5 x 5 mm raster at z = 0.

Someone review this please :-) @rahmans1 @cameronc137

**Comment by wdconinc** [comment]
After latest change to default settings we now have a 2.5 x 2.5 mm raster, with 136 urad/mm correlation and with generation at 7.75 m upstream from the target. This results in the following default beam positions at z = 0 (top), and at z = -7.75 m (bottom).

I sort of expected a point source at -7.75 m based on the physics of the raster... Seems like with these correlations the focus is at 3.68 m upstream. Anyway, I'll consider this working and ready for merging.

![raster_correlation_z0](https://user-images.githubusercontent.com/4656391/53433083-bd5d7200-39c1-11e9-8b46-509930d568ce.png)

![raster_correlation_zg](https://user-images.githubusercontent.com/4656391/53433084-bd5d7200-39c1-11e9-8382-b51e5fdcdc06.png)

**Comment by wdconinc** [comment]
Merged into develop.
