### ISSUE TITLE
Default raster size should be 5 mm x 5 mm

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#213]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop, release_candidate_v2.1
- revision (HEAD for most recent): HEAD

### Expected Result: (what do you expect when you execute the steps above)
Actual raster should be 5 mm x 5 mm full size.

### Actual Result: (what do you get when you execute the steps above)
Current raster set to 2.5 mm  x 2.5 mm because was assumed that +/- 2.5 mm.

**Comment by wdconinc** [comment]
FYI, procedure for this is now to create bugfix branch, merge it into both develop and release_candidate_v2.1.

**Comment by wdconinc** [comment]
@rahmans1 Is the angle correlation still correct?

**Comment by wdconinc** [comment]
340 urad is largest angle for external raster position.

**Comment by wdconinc** [comment]
Raster is to be defined at upstream target window, not z = 0. Need to implement /remoll/evgen/beam/rasplane <pos>

**Comment by cameronc137** [comment]
I know its been written somewhere and I should know it, but a catalog of the existing, and previously used definitions of raster (i.e. /remoll/oldras true or false, and this new version of raster macro commands) and what they do (and which generators they worked in) would be appreciate.

For reference, can this be verified as at least not wrong, I am using for envelope production: 
`/remoll/oldras false
/remoll/rasx 5 mm
/remoll/rasy 5 mm`

**Comment by wdconinc** [comment]
While putting in the raster reference z position, found a sign error (in both raster generation and plotting; so wasn't caught earlier). How the plots below at (default raster settings) the point of generation, US target window, center of target, DS target window. Raster is indeed 5 mm x 5 mm (+/-2.5 mm x +/-2.5 mm), with +/-340 urad x +/-340 urad expands through the target to be about +/-3 mm x +/-3 mm at DS window. Focus of raster is indeed closer to -7.75 m, at z = zg (first plot below)

![raster_correlation_zg](https://user-images.githubusercontent.com/4656391/53609845-cd7a7a80-3b96-11e9-87e4-127cb0d6f8e9.png)
![raster_correlation_zu](https://user-images.githubusercontent.com/4656391/53609846-cd7a7a80-3b96-11e9-89df-572d1e1ef85a.png)
![raster_correlation_z0](https://user-images.githubusercontent.com/4656391/53609847-cd7a7a80-3b96-11e9-8907-322d01ef655e.png)
![raster_correlation_zd](https://user-images.githubusercontent.com/4656391/53609848-cd7a7a80-3b96-11e9-9910-542caba1dab3.png)

**Comment by rahmans1** [comment]
@wdconinc This looks great. Could you please merge the changes to develop? I was hoping to run some new sims tonight.

**Comment by wdconinc** [comment]
Fixed in f47a91b12acd416f1d503a0d11616175c2b32aca 

@cameronc137 Not fixing your request since not related to remollGenBeam, which this issue is about. Will put into separate issue.
