### ISSUE TITLE
Pion branch stores hits with x,y,z outside detector volume

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#22]
The pion branch stores detectors in the cylindrical disks that act as PMTs. These are only 1 mm thick. However, when running the simulation, hits are created in this detector with a variety of hit.x,y,z values outside the disk. Could this be because we get the x,y,z from the G4Step prestep point? Should we use the poststep point?

Image below should only have hits in the disk shaped region on the right. Hits distributed in the middle and to the left are far outside of the PMT volume.

![photons_45_degree_photo_cathode](https://cloud.githubusercontent.com/assets/4656391/23774562/45b824bc-04f2-11e7-9828-d3e144d001d3.png)

**Comment by wdconinc** [comment]
@seamusriordan @yxzhao88 This is something that should be mentioned in the simulation meeting as it has the potential to affect other analyses. We discussed it briefly this morning in the pion detector meeting and it was suggested we should alert others of the issue. I'm not sure yet whether using poststep point is the correct solution (though it is what basic example B2a uses, the first one to introduce hits):
```
newHit->SetPos (aStep->GetPostStepPoint()->GetPosition());
```

**Comment by wdconinc** [comment]
After changing to poststep point, I'm getting much better results.

![poststetp_point](https://cloud.githubusercontent.com/assets/4656391/23820576/6f059c3a-05e9-11e7-9eda-17322c1f9a86.png)

**Comment by seamusriordan** [comment]
Yes, that looks very nice.  I think the use of of prestep was a bad habit of mine.  Also I'll note yxzhao88 has moved on to a job at INFN

**Comment by wdconinc** [comment]
Can't reproduce this issue. Probably independent of prestep/poststep, and may have been caused by some transients in my code. Closing for now, but feel free to reopen if anything like this shows up for someone...

Verified that master branch has no issues like this for hit.det==28. Prestep point results in getting the entry point to the detector. Poststep point gets the exit point from the detector. There will always be a step point on fGeomBoundary. The important thing is to get the position from the prestep/poststep point that the fGeomBoundary test is done on. That's done correctly in remoll.

**Comment by wdconinc** [comment]
Duplicate of closed #127
