### ISSUE TITLE
Add large acceptance fields to cmake download list

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#221]
Locations:
https://hallaweb.jlab.org/12GeV/Moller/downloads/remoll/hybridSymmetric_sensR_0.0.txt
https://hallaweb.jlab.org/12GeV/Moller/downloads/remoll/upstreamSymmetric_sensR_0.0.txt
MD5 sums:
0f6e9a3a8392d01c63f1609afc4e4c09  hybridSymmetric_sensR_0.0.txt                                                                                                                   
4ca3d968cadd85a89b86148411eda678  upstreamSymmetric_sensR_0.0.txt                                                                                                                 

**Is your feature request related to a problem? Please describe.**
Current field maps are limited in r.

**Describe the solution you'd like**
For simulations of low energy tracks at larger r, we need fields at larger r.

**Describe alternatives you've considered**
We could simply direct users to the website or add a make target to download additional fields. However, downloading directly is not as much overhead for 18Mb fields.

**Comment by wdconinc** [comment]
@cipriangal I'll let you decide which maps are appropriate to upload and add here.

**Comment by rahmans1** [comment]
@cipriangal Could you please let me know upto what radius in r you want the field maps to be generated in? Also the level of coarseness in azimuthal direction? We can increase the number of steps in theta for the outer fringe or leave it the same as in the main region.

**Comment by wdconinc** [comment]
Resolved and working with #338.
