### ISSUE TITLE
Default beam current is 75 uA

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#222]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD
- OS or system: all
- Special ROOT or Geant4 versions? no

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Run macros/tests/commit/test_power.mac (which does not specify current)
2. Analyze output with analysis/tests/test_power.C (which assumes 85 uA current)

### Expected Result: (what do you expect when you execute the steps above)
Power should be correct.

### Actual Result: (what do you get when you execute the steps above)
Power listed in W/85 uA is incorrect.

Relevant line:
https://github.com/JeffersonLab/remoll/blob/c26e88903d11fe49553a0f8f7bbae991a4f1c42c/include/remollglobs.hh#L18

Other context: modifying test_power.C to retrieve actual current (and nentries for that matter) from tree may be required.

**Comment by wdconinc** [comment]
Essentially, we need to decide whether the default current should be 85uA.

**Comment by chandabindu** [comment]
I was using 85 uA, just to reproduce Rakitha's 2016 result which was for 85uA current. 
MOLLER proposed to run with 75 uA.

I would not prefer to keep 75 uA and I'll do all future power calculations for 75uA.

**Comment by wdconinc** [comment]
Ok. Closing.
