### ISSUE TITLE
hit.r distribution on det 28 is incorrect as of b14e744cfb46f5763fec3140f88105fa7393e6e2

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#228]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop, release-candidate-v2.1.0
- revision (HEAD for most recent): https://github.com/JeffersonLab/remoll/commit/b14e744cfb46f5763fec3140f88105fa7393e6e2
- OS or system: linux
- Special ROOT or Geant4 versions? 4.10.05

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. `scripts/tests/test_macros.sh commit test_moller.mac`
2. Check rootfiles/tests/commit/analysis/test_moller_h_hit_r.png

### Expected Result: (what do you expect when you execute the steps above)
Commit right before (11f59cc74a2f1ee8a17263b342d10d48a711fa28)
![image](https://user-images.githubusercontent.com/4656391/54614473-dbebe180-4a32-11e9-8b61-7cd3c784a7bc.png)

### Actual Result: (what do you get when you execute the steps above)
Commit in question (b14e744cfb46f5763fec3140f88105fa7393e6e2)
![image](https://user-images.githubusercontent.com/4656391/54614328-97f8dc80-4a32-11e9-8cf7-2c989c6b841d.png)

**Comment by wdconinc** [comment]
Full diff that causes this:
```
diff --git a/geometry/mollerMother.gdml b/geometry/mollerMother.gdml
index 6a37cd05..7ab7a386 100644
--- a/geometry/mollerMother.gdml
+++ b/geometry/mollerMother.gdml
@@ -5,21 +5,20 @@
      <position unit="mm" name="targetCenter" x="0" y="0" z="0"/>
      <position unit="mm" name="upstreamCenter" x="0" y="0" z="7000."/>
      <position unit="mm" name="hybridCenter" x="0" y="0" z="13366.57"/>
-     <position unit="mm" name="trackingCenter" x="0" y="0" z="25635."/>
+     <position unit="mm" name="trackingCenter" x="0" y="0" z="26635."/>
      <position unit="mm" name="detectorCenter" x="0" y="0" z="28500."/>
-     <position unit="mm" name="showerMaxDetectorCenter" x="0" y="0" z="31000."/>
-     <position unit="mm" name="pionDetectorCenter" x="0" y="0" z="32000."/>
+     <position unit="mm" name="showerMaxDetectorCenter" x="0" y="0" z="28750."/>
+     <position unit="mm" name="pionDetectorCenter" x="0" y="0" z="29600."/>
 </define>
 
 <materials>
```

I can hear the collective 'huh?!?'.

**Comment by cameronc137** [comment]
Maybe the shower max detector is overlapping/in front of the 28.5 meter detector 28?

**Comment by wdconinc** [comment]
Shouldn't be possible to have overlap between material world and parallel world. That's the point, after all.

**Comment by wdconinc** [comment]
But, yeah, that's exactly what it looks like. Also, overlap check doesn't catch it.

**Comment by cameronc137** [comment]
I guess I mean that the material of the shower max could be on top of where the main detector ring is, and so we are just getting a snapshot of the showering instead of unaffected regular electron flux. 

Also, the main detector array is centered at 28.5 m but has +- 500cm in both directions at least (uncertain due to still undetermined parameters that will be optimized one day).

**Comment by wdconinc** [comment]
Ah, I see what you mean. Interesting observation and indeed a possibility. Let me check.

**Comment by wdconinc** [comment]
I think you are almost exactly right. The showermax is SCALE_UP*SCALE_UP*(2.0*showerMaxDetectorLength) wide in z, with showerMaxDetectorLength 12 cm (and SCALE_UP 101%) for a total of 24.4824 cm. With a distance of 25 cm between the main detector plane at 28.5 m and the shower detector central plane at 28.75 m (and remembering that only half of the showermax is at z lower than 28.75 m), this means that it's not quite that we have the virtual main detector plane inside the showermax as that we are getting substantial backsplash. We might want to plot only the higher energy tracks, I guess.

**Comment by wdconinc** [comment]
Voila, splitting hits in the main detector at 28.5 m up between forward and backward moving particles, we recover the original plot:
![image](https://user-images.githubusercontent.com/4656391/54620508-a815b980-4a3c-11e9-9c46-e7c434832c40.png)
Yes, backscattered hits are off the scale in this geometry.

**Comment by wdconinc** [comment]
Proposed fix is to separate gammas from other particles. Here's the more than 1 MeV gamma plot:
![image](https://user-images.githubusercontent.com/4656391/54621673-80275580-4a3e-11e9-9540-bc139ebe32e5.png)
