### ISSUE TITLE
Do check for same detector numbers and exit out if two detectors have the same ID

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/remoll#324]
**Is your feature request related to a problem? Please describe.**
we should not allow two detectors with the same ID

**Describe the solution you'd like**
Do check for same detector numbers and exit out if two detectors have the same ID

**Describe alternatives you've considered**
maybe modify DetectorConstruction to always print det IDs and rely on users to check (that seems prone to problems)

**Additional context**

**Comment by wdconinc** [comment]
We'd tried to solve this using administrative controls rather than engineered controls. There are cases when we want multiple volumes to have the same ID (I think we identified power deposition in a set of collimator or shielding volumes). We did set a number of ranges for each subsystem (<100 was for parallel world, 1000s for target, etc, to 8000s for pion detector). We even documented that, but I can't find where... :-(

**Comment by cipriangal** [comment]
tried to set the verbosity on the geometry to 1 to be able to see if i had any overlaps and nothing printed out. i'll take another look today and if i get it to work i'll close this out

**Comment by cipriangal** [comment]
ok .. using 
```
/remoll/geometry/verbose 2
```
doesn't print out the actual detector id numbers; 
I'll leave this open until i have some time to write this up (or someone else fixes it)

**Comment by wdconinc** [comment]
Now I recall why this was not always a good idea: every single detector has multiple volumes that use the same DetNo, so there are about 2600 lines of output when running with parametrized detector.
```
...
G4WT1 > remoll: DetNo 51058 for pmtVol_51008
G4WT1 > remoll: already used by refVol_51008
G4WT1 > remoll: DetNo 51059 for lgVol_51009
G4WT1 > remoll: already used by refVol_51009
G4WT0 > remoll: already used by refVol_50001
G4WT0 > remoll: DetNo 52053 for lgVol_52003
G4WT0 > remoll: already used by refVol_52003
G4WT1 > remoll: DetNo 51059 for pmtVol_51009
G4WT1 > remoll: already used by refVol_51009
G4WT1 > remoll: DetNo 51060 for lgVol_51010
G4WT1 > remoll: already used by refVol_51010
G4WT0 > remoll: DetNo 52053 for pmtVol_52003
G4WT0 > remoll: already used by refVol_52003
G4WT0 > remoll: DetNo 52054 for lgVol_52004
G4WT1 > remoll: DetNo 51060 for pmtVol_51010
G4WT1 > remoll: already used by refVol_51010
G4WT1 > remoll: DetNo 51061 for lgVol_51011
G4WT1 > remoll: already used by refVol_51011
G4WT0 > remoll: already used by refVol_52004
G4WT0 > remoll: DetNo 52054 for pmtVol_52004
G4WT0 > remoll: already used by refVol_52004
G4WT0 > remoll: DetNo 52055 for lgVol_52005
G4WT0 > remoll: already used by refVol_52005
G4WT0 > remoll: DetNo 52055 for pmtVol_52005
G4WT0 > remoll: already used by refVol_52005
G4WT1 > remoll: DetNo 51061 for pmtVol_51011
G4WT1 > remoll: already used by refVol_51011
G4WT1 > remoll: DetNo 51062 for lgVol_51012
G4WT1 > remoll: already used by refVol_51012
G4WT1 > remoll: DetNo 51062 for pmtVol_51012
G4WT1 > remoll: already used by refVol_51012
G4WT1 > remoll: DetNo 51063 for lgVol_51013
G4WT1 > remoll: already used by refVol_51013
...
```

However, this probably is indeed a problem to be solved in the parametrized detector implementation (@rahmans1)

**Comment by cipriangal** [comment]
ok ... then maybe the solution is to check and print the volumes that have the same id

**Comment by wdconinc** [comment]
Yes, as in #325.

**Comment by cipriangal** [comment]
great. i must have not searched for the right thing
