### ISSUE TITLE
Use Thomas-BMT spin tracking equations of motions

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#36]
In order to study PMT DD type effects as observed by Qweak, we will need to be able to study longitudinal and transverse polarization tracking through the magnetic fields using the Thomas-BMT equations of motion.

This is how Qweak implements this in https://qweaksvn.jlab.org/repos/Simulation/trunk/QWGEANT4/src/QweakSimDetectorConstruction.cc

```
#define TRACK_ELECTRON_SPIN
#ifdef  TRACK_ELECTRON_SPIN
  fGlobalEquation = new G4Mag_SpinEqRhs(pMagneticField);
  G4int numberOfVariables = 12;
#else
  fGlobalEquation = new G4Mag_UsualEqRhs(pMagneticField);
  G4int numberOfVariables = 6;
#endif

  // taken from one of the Geant4 presentation:
  // - If the field is calculated from a field map, a lower order stepper
  //   is recommended: the less smooth the field is, the lower the order of the
  //   stepper that should be used. For very rough fields one should use 1st order
  //   stepper, for a somewhat smooth field one must choose between 1st and 2nd
  //   order stepper.

  //fGlobalStepper  = new G4ClassicalRK4(fGlobalEquation, numberOfVariables);  // classical 4th order stepper
  //fGlobalStepper  = new G4ExplicitEuler(fGlobalEquation, numberOfVariables); //           1st order stepper
  //fGlobalStepper  = new G4ImplicitEuler(fGlobalEquation, numberOfVariables); //           2nd order stepper
  fGlobalStepper  = new G4SimpleRunge(fGlobalEquation, numberOfVariables);   //           2nd order stepper


  // Provides a driver that talks to the Integrator Stepper, and insures that
  //   the error is within acceptable bounds.
  G4MagInt_Driver* fGlobalIntgrDriver = new G4MagInt_Driver(0.1*mm,  //1.0e-3*mm,
							    fGlobalStepper,
							    fGlobalStepper->GetNumberOfVariables());

  fGlobalChordFinder = new G4ChordFinder(fGlobalIntgrDriver);



  //       G4bool fieldChangesEnergy = false;
  //       G4FieldManager* pFieldMgr = new G4FieldManager(myField,pChordFinder,FieldChangeEnergy);
  //       LocalLogicalVolume = new G4LogicalVolume(shape, material,"name",pFieldMgr,0,0);

  //   // minimal step of 1 mm is default
  //   fMinStep = 0.01*mm ;
  //
  //   fGlobalChordFinder = new G4ChordFinder (pGlobalMagnetField,
  //                                           fMinStep,
  //                                           fGlobalStepper);

  fGlobalFieldManager->SetChordFinder(fGlobalChordFinder);
```

**Comment by wdconinc** [comment]
More details about field management in F04

**Comment by cipriangal** [comment]
Should this be a separate branch until we figure if the DD is an issue for MOLLER? The additional calculations would be a waste of computing time if it's not needed. 

Also if you (@wdconinc ) working on the B-field interactions I can put together the output.

**Comment by wdconinc** [comment]
Will be a separate branch, will be off by default. Will also not matter computationally since most of (at least Qweak) computation effort goes to field lookups, not evaluation of the EOMs. At least that was the case 5 years ago. I don't think it has changed with hardware. Maybe geant4 has gotten smarter with caching, though (simultaneous regional propagation instead of track by track).

**Comment by wdconinc** [comment]
Re: caching, F04 uses G4Cache<GlobalField*> to speed this up somewhat.

**Comment by wdconinc** [comment]
My general (overly optimistic) philosophy is that even by-default-unused functionality, once developed for a single study, is more likely to remain usable if it is merged into a mainline branch.

If we develop spin precession tracking (which we have to do anyway to assess how much of an issue DD will be), and then leave it on a side branch that doesn't get developed further, it will get out of sync so badly that when we decide to look into this again we won't be able to reuse any of the work.

That doesn't mean that we can't cull old cruft, and it doesn't mean it should be enabled by default, but it should remain a) compileable and b) remain part of other paradigms in the code (io, messenger, threading).

**Comment by cipriangal** [comment]
That makes sense. 

I was thinking more in terms of the output; having a polarization vector for each particle hit will add up (although I guess we can do something intelligent and not save those vectors unless the polarization is higher than some value).

**Comment by wdconinc** [comment]
Branch feature-spin-precession

**Comment by wdconinc** [comment]
Branch feature-spin-precession

**Comment by wdconinc** [comment]
Yeah, I didn't finish this work yet. Here are the outstanding issues:
- I don't really know how to assign the spin in the generator since you're supposed to give the spin in the lab frame. I suspect that, in Moller scattering, one electron will undergo a spin flip due to the photon emission while the other one is just unpolarized. That would result in a dilution at the detectors.
- I haven't yet written the code to store the spin component in the hit. Until then, those hit.sx etc values will remain uninitialized (I'm actually surprised they're not all exactly zero or all complete garbage).

**Comment by wdconinc** [comment]
I'll let you handle the first point since you appear to have figured it out. I'll do the second point.

**Comment by wdconinc** [comment]
Oh, and I don't think whatever is in `part` is passed to the actual particles yet. It's just stored in the ROOT tree and vector.

**Comment by cipriangal** [comment]
good point .. fixed: https://github.com/JeffersonLab/remoll/commit/0bdf9161e9e900806e48550f71a78696c193f42e

**Comment by wdconinc** [comment]
Not sure if G4ThreeVector(0,0,1) as polarization for an electron with nonzero scattering angle is correct...

**Comment by wdconinc** [comment]
I was thinking
```
    G4ThreeVector x1(0.0,0.0,0.0);
    G4ThreeVector p1(pperp*cos(phcom), pperp*sin(phcom), gamma_com*(ppar + e_com*beta_com));
    G4ThreeVector s1 = p1.unit();
    evt->ProduceNewParticle(x1, p1, "e-", s1);

    G4ThreeVector x2(0.0,0.0,0.0);
    G4ThreeVector p2(-pperp*cos(phcom), -pperp*sin(phcom), gamma_com*(-ppar + e_com*beta_com));
    G4ThreeVector s2 = p2.unit();
    evt->ProduceNewParticle(x2, p2, "e-", s2);
```

**Comment by wdconinc** [comment]
@cipriangal I'll have to postpone fixing this until tomorrow or so. If you can fix it, feel free.

**Comment by cipriangal** [comment]
Worked on it some but I can't seem to get it to work. The particleGun reports back that particles are polarized, but when I interrogate about the same particles (can tell from the momentum) in the steppingAction it says the polarization vector is all 0s. 

Will look at it further this afternoon.

**Comment by wdconinc** [comment]
I think the issue is related to what
```
/remoll/field/equationtype 3
/remoll/field/steppertype 0
```
does. When you start up, remollGlobalField creates the equation, stepper, chordfinder (in that order) and registers them with the field manager. When you set a different equation or stepper, it doesn't regenerate the chordfinder. I was fiddling with this yesterday but couldn't quite make it work. I'll see if I can at least commit my changes. For now it may be more re-instantiation and deletion of pointers than needed, but at least it should regenerate the whole stack of things every time.

**Comment by wdconinc** [comment]
Confirmed seems to work now. macros/test/unit/test_polarization.mac gives me:
![image](https://user-images.githubusercontent.com/4656391/40147639-7a519474-5938-11e8-8c0d-83094bd1fa5c.png)
That's with a change to GenMoller though.

**Comment by cipriangal** [comment]
Awesome. I'll do some tests tomorrow and hopefully get to present something on Friday.

**Comment by cipriangal** [comment]
@wdconinc: It looks like the only things that have a polarization are photons:
![screen shot 2018-05-17 at 11 07 12 am](https://user-images.githubusercontent.com/8987591/40186200-86b76880-59c2-11e8-8c4b-5ff07174d762.png)

We are still at the problem I reported yesterday: the particle gun tells me that the particle have !=0 polarization but the stepping action tells me it's 0.

**Comment by wdconinc** [comment]
Ok, figured this one out. Fixed in 3744ae8

![image](https://user-images.githubusercontent.com/4656391/40201921-82b5fd6a-59ee-11e8-9453-87312943f1df.png)

**Comment by cipriangal** [comment]
Confirmed. I'll update the generator with proper longitudinal/transverse polarization.

**Comment by cipriangal** [comment]
This commit should fix the polarization direction. However with the runexample.mac I get:
```
/home/ciprian/moller/otherRemoll/remoll/src/remollMagneticField.cc line 397: ERROR bad conversion to cylindrical coordinates
Point  ( -nan, -nan, -nan ) m
```
will try to look into it later tonight.

**Comment by wdconinc** [comment]
`/remoll/setequation 2` instead of `/remoll/setequation 3`

Equation 1 and 3 only work with electric fields. Since our remollGlobalField inherits from G4MagneticField, not G4ElectroMagneticField, we don't support those. I guess we should warn about that.

**Comment by wdconinc** [comment]
I meant `/remoll/field/equationtype 2`

**Comment by cipriangal** [comment]
Thanks! That did it. It's funny that a couple of events did manage to do through with eqtype 3. 

I will run this tonight and try to compare with the analytic equation Don found for Qweak.

**Comment by wdconinc** [comment]
@cipriangal Did this produce results that looked sensible? If so, we can merge into develop after 2.0.0 is out.

**Comment by cipriangal** [comment]
I think we are good, but just let me talk this over with Kent to make sure I didn't miss anything. I'll let you know by the end of the day.

**Comment by cipriangal** [comment]
@wdconinc: Had a chat with Kent about it and while I still have quite a few plots to make to ensure things make sense, we should definitely put this in the new release. If we later find it needs corrections we can just fix them in master directly.

I'll leave this open until you merge it in the release.
