### ISSUE TITLE
Visualization does not work out of the box

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/remoll#38]
To quote the readme:
> Visualization macros are found in vis/
> To run, execute
> ./remoll 
> which should bring up a graphical command interface
> To see the geometry you have to say:
> /run/initialize
> then 
> /control/execute macros/vis.mac

I'm on a RHEL7 gcc 4.8.5, ROOT 5.34/36, G4.10.2.2. Fresh copy of the repo. 

Running the visualizer from the main directory or the build directory gives:
>***** Illegal application state </remoll/setgeofile geometry_dose/mollerMother.gdml> *****
>***** Batch is interrupted!! *****

**Comment by wdconinc** [comment]
Hotfix branch hotfix_issue38_visualization. Issue solved there. Will merge into master after testing.

**Comment by wdconinc** [comment]
@cipriangal can you give a review to PR https://github.com/JeffersonLab/remoll/pull/41 ? Then I can merge into master and release bug fix.

**Comment by wdconinc** [comment]
Closed through #41.
