### ISSUE TITLE
Geometry overlap internal to hybrid/hybridDaughter_merged.gdml

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#383]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD 5656858ef608cc7ebfa7e934c11650011ac796b8
- OS or system: Linux ubuntu 20.04
- Special ROOT or Geant4 versions? Just the usual

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. cd geometry
2. gdmlview -o -c hybrid/hybridDaughter_merged.gdml

### Expected Result: (what do you expect when you execute the steps above)
Expect no overlaps.

### Actual Result: (what do you get when you execute the steps above)
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume DSpipe2_USplate:0 (G4Polycone)
          with DSpipe2_DSpipe2_1:0 (G4Polycone) volume's
          local point (142.876,-484.289,3.81296), overlapping by at least: 7.52786 um 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------


-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume DSpipe2_DSpipe2_1:0 (G4Polycone)
          with DSpipe2_USplate:0 (G4Polycone) volume's
          local point (244.444,441.71,21.6526), overlapping by at least: 88.254 um 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

**Comment by wdconinc** [comment]
![image](https://user-images.githubusercontent.com/4656391/93672247-02973800-fa6f-11ea-985e-b368a70e58b4.png)

**Comment by chandabindu** [comment]
Yes, I saw this overlap warning while I was testing the other day.
This has happened most likely due to new epoxy implementation on the magnets.
Anyway, there is a plan to make the upstream two-bounce shield better to avoid (or optimized) the downstream two-bounce shield.
I'll take care of this while I'll work in the downstream region.

**Comment by chandabindu** [comment]
Fixed!!
