### ISSUE TITLE
Geometry overlap internal to hall/hallDaughter_dump.gdml

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#384]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): 5656858ef608cc7ebfa7e934c11650011ac796b8
- OS or system: Linux ubuntu 20.04
- Special ROOT or Geant4 versions? Just the usual

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. cd geometry
2. gdmlview -o -c hall/hallDaughter_dump.gdml

### Expected Result: (what do you expect when you execute the steps above)
Expect no overlaps.

### Actual Result: (what do you get when you execute the steps above)
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume hallFlatLidDet:0 (G4Tubs)
          with topWall:0 (G4SubtractionSolid) volume's
          local point (-6291.17,25648.1,47652.7), overlapping by at least: 50 um 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------


-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume topWall:0 (G4SubtractionSolid)
          with hallFlatLidDet:0 (G4Tubs) volume's
          local point (3770.13,25485.7,-1.56055e-12), overlapping by at least: 50 um 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```
```

**Comment by wdconinc** [comment]
![image](https://user-images.githubusercontent.com/4656391/93673202-d54b8980-fa70-11ea-900b-64558b9f26de.png)

**Comment by cipriangal** [comment]
Yeah, this should be fixed. I'll make a hotfix branch for it sometime this week. Thanks for pointing it out

**Comment by cipriangal** [comment]
this branch: https://github.com/JeffersonLab/remoll/tree/hotfix-hallFlatLidDet-overlap
should fix the issue. 

Couldn't get gdmlview to work(compile) on the system i working so @wdconinc  if you get a chance could you check and if it's ok we can merge this into develop.

I'll leave it up to you to close the issue.

**Comment by wdconinc** [comment]
Confirmed no overlap.
