### ISSUE TITLE
ShowerMax region overlap

### ISSUE THREAD

**Issue by chandabindu** [JeffersonLab/remoll#419]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): 
- OS or system: ifarm
- Special ROOT or Geant4 versions? ROOT6.20.04; GEANT44.10.06.p02MT

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Using checkoverlap.mac macro
2. 

### Expected Result: (what do you expect when you execute the steps above)
There should be no overlap.

### Actual Result: (what do you get when you execute the steps above)
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume singledet_0:416 (G4UnionSolid)
          with singledet_1:429 (G4UnionSolid) volume's
          local point (94.0316,-134.799,-29.7913), overlapping by at least: 1.00308 mm 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume singledet_1:429 (G4UnionSolid)
          with singledet_0:416 (G4UnionSolid) volume's
          local point (98.0578,131.872,31.7717), overlapping by at least: 3.92995 mm 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

**Comment by wdconinc** [comment]
Known issue but I can't fix the showermax design.

**Comment by wdconinc** [comment]
Resolved in updated showermax geometry in  bcd013dd3bb00f684d9917649aa78a7482f72612.
