### ISSUE TITLE
Accidental commit and push

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#43]
I just accidentally pushed into JeffersonLab/remoll/develop. I didn't pay enough attention to where my git push was still pointing. This last commit should simply be undone: Commit # 1add254a8e1347b49bfbb734a9d00d94fff2e8fb should be reset back to # 0e37474b94d100903795baf2c243eac0c42eac99

**Comment by wdconinc** [comment]
#0e37474 is on master, not develop.

**Comment by cameronc137** [comment]
Ah, then this one: ae22c1ab88ac8194507d8cb5a6e76a9932571f33

**Comment by wdconinc** [comment]
```
git reset HEAD^ --hard
git push origin -f
```
