### ISSUE TITLE
Segmentation fault when using downstream field map with maximum radial extent 75 cm 

### ISSUE THREAD

**Issue by rahmans1** [JeffersonLab/remoll#453]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): 02e7236a
- OS or system: Beluga server
module load StdEnv/2020
module load gcc/9.3.0
module load geant4/10.06
module load root/6.20.04
module load boost/1.72.0
module load cmake/3.18.4
 
- Special ROOT or Geant4 versions? 

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Use the V2DSg.9.75cm.txt for running instead of the default downstream map V2DSg.9.txt. Field maps are located in  
/home/rahmans/projects/rrg-jmammei/MOLLER_FIELDMAPS on beluga. Example macro:

/remoll/setgeofile geometry/mollerMother.gdml
/remoll/physlist/register QGSP_BERT_HP
/remoll/physlist/parallel/enable
/remoll/parallel/setfile geometry/mollerParallel.gdml
/run/numberOfThreads 5
/run/initialize
/remoll/addfield map_directory/V2DSg.9.75cm.txt
/remoll/addfield map_directory/V2U.1a.txt
/remoll/evgen/set moller
/remoll/oldras false
/remoll/beamene 11 GeV
/remoll/beamcurr 85 microampere
/remoll/SD/disable_all
/remoll/SD/enable 28
/remoll/SD/detect lowenergyneutral 28
/remoll/SD/detect secondaries 28
/remoll/SD/detect boundaryhits 28
/remoll/kryptonite/volume lefthut_Det_inside_logic
/remoll/kryptonite/volume righthut_Det_inside_logic
/remoll/kryptonite/enable
/remoll/filename /lustre03/project/6049248/REMOLL/raw_output/fineFieldStudies/out/V2U.1a.50cm_V2DSg.9.75cm/moller_17216350_1.root
/run/beamOn 50000

### Expected Result: (what do you expect when you execute the steps above)
The simulation runs without crashing.  

### Actual Result: (what do you get when you execute the steps above)
Simulation crashes within the first 5K events with segmentation fault. 
```

G4WT3 > remoll: or use the following in your macro:
G4WT3 > remoll:   /remoll/SD/detect boundaryhits 4001

 *** Break *** segmentation violation

 *** Break *** segmentation violation

 *** Break *** segmentation violation

 *** Break *** segmentation violation

 *** Break *** segmentation violation
Program remoll finished with exit code 139 at: Sat Mar 20 12:18:02 EDT 2021


```

**Comment by wdconinc** [comment]
`Warning volume righthut_Det_inside_logic unknown`

**Comment by rahmans1** [comment]
> `Warning volume righthut_Det_inside_logic unknown`

Shouldn't cause a problem. Just a warning.

**Comment by wdconinc** [comment]
1. Reproduced issu on avx-512 instruction set (but no debugging and no valgrind)
2. Reproduced issue on avx-2 instruction set (still no debugging, but at least valgrind)
3. Reproduced on laptop.

**Comment by wdconinc** [comment]
@rahmans1 Can you confirm when you are confident that this is fixed?

**Comment by rahmans1** [comment]
> @rahmans1 Can you confirm when you are confident that this is fixed?

Yes. Running new batch of simulations now with large statistics. Will confirm by end of today.

**Comment by rahmans1** [comment]
![MollerNew](https://user-images.githubusercontent.com/7409132/112436741-179d9e00-8d14-11eb-99d5-42ad588e6c6a.JPG)
No job failures with 75 cm maps after the fix has been applied. Radial distribution for mollers almost identical to the 50 cm case ran previously before the fix.

**Comment by rahmans1** [comment]
> @rahmans1 Can you confirm when you are confident that this is fixed?

Fixed.
