### ISSUE TITLE
Seg. Fault in Visualization mode

### ISSUE THREAD

**Issue by rakithab** [JeffersonLab/remoll#485]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): 
- OS or system: Ubuntu 20.04.2 LTS
- Special ROOT or Geant4 versions? geant4.10.07.p01 and root_v6.22.08

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. ./build/remoll
2. click initialize

### Expected Result: (what do you expect when you execute the steps above)
GUI should not crash and we should be able to click viewer->Qt Viewer

### Actual Result: (what do you get when you execute the steps above)
Seg. Fault
[clement_prompt_G4_vis_4_2021_output.txt](https://github.com/JeffersonLab/remoll/files/6406188/clement_prompt_G4_vis_4_2021_output.txt)

**Comment by rakithab** [comment]
`Reading mollerMother.gdml
- schema validation off
- overlap check off

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 9 (Thread 0x7f9f20d5d700 (LWP 2866)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55a75592e938) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55a75592e8e8, cond=0x55a75592e910) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55a75592e910, mutex=0x55a75592e8e8) at pthread_cond_wait.c:638
#3  0x00007f9f22b5cb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f9f22b5c75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 8 (Thread 0x7f9f2155e700 (LWP 2865)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55a75592e938) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55a75592e8e8, cond=0x55a75592e910) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55a75592e910, mutex=0x55a75592e8e8) at pthread_cond_wait.c:638
#3  0x00007f9f22b5cb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f9f22b5c75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7f9f21d5f700 (LWP 2864)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55a75592e938) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55a75592e8e8, cond=0x55a75592e910) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55a75592e910, mutex=0x55a75592e8e8) at pthread_cond_wait.c:638
#3  0x00007f9f22b5cb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f9f22b5c75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f9f22560700 (LWP 2863)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55a75592e938) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55a75592e8e8, cond=0x55a75592e910) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55a75592e910, mutex=0x55a75592e8e8) at pthread_cond_wait.c:638
#3  0x00007f9f22b5cb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f9f22b5c75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f9f30c74700 (LWP 2860)):
#0  0x00007f9f4ecf9aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9f48df536e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9f48df54a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9f4a529565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f9f4a4d04db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f9f4a308785 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f9f34157efa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f9f4a3099d2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f9f31523700 (LWP 2859)):
#0  0x00007f9f4ecf9aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9f48df536e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9f48df56f3 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9f322a4f8a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f9f48e1ead1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f9f31d24700 (LWP 2858)):
#0  0x00007f9f4ecf9aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9f48df536e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9f48df54a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9f48df54f1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f9f48e1ead1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f9f3385d700 (LWP 2857)):
#0  0x00007f9f4ecf9aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9f4964ac1a in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f9f4964c90a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f9f3429b298 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f9f4a3099d2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f9f4b7db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f9f4ed06293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f9f460ba1c0 (LWP 2840)):
#0  0x00007f9f4ecc9dff in wait4 () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9f4ec390e7 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f9f4fd4289e in TUnixSystem::StackTrace() () from /home/cde/root/root/lib/libCore.so.6.22
#3  0x00007f9f4fd3f725 in TUnixSystem::DispatchSignals(ESignals) () from /home/cde/root/root/lib/libCore.so.6.22
#4  <signal handler called>
#5  0x00007f9f4f5eeab5 in G4UIQt::ReceiveG4cout(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#6  0x00007f9f4f0b3782 in G4coutDestination::ReceiveG4cout_(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4global.so
#7  0x00007f9f4f149651 in G4strstreambuf::sync() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#8  0x00007f9f4ef25a43 in std::ostream::flush() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f9f4eb566ff in G4GDMLRead::Read(G4String const&, bool, bool, bool) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4persistency.so
#10 0x00007f9f4ffa2090 in G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x55a75531ad20) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:35
#11 G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x55a75531ad20) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:31
#12 remollDetectorConstruction::ParseGDMLFile (this=0x55a75531abf0) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:544
#13 0x00007f9f4ffa2e85 in remollDetectorConstruction::Construct (this=0x55a75531abf0) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:912
#14 0x00007f9f4f1a853e in G4RunManager::InitializeGeometry() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#15 0x00007f9f4f1a82e4 in G4RunManager::Initialize() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#16 0x00007f9f4f1c620d in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#17 0x00007f9f4f12535f in G4UIcommand::DoIt(G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#18 0x00007f9f4f142c9a in G4UImanager::ApplyCommand(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#19 0x00007f9f4f5fd89f in G4VBasicShell::ExecuteCommand(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#20 0x00007f9f4f602ade in G4VBasicShell::ApplyShellCommand(G4String const&, bool&, bool&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#21 0x00007f9f4f5f5aa4 in G4UIQt::ButtonCallback(QString const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#22 0x00007f9f4a4fd458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f9f4b03c3e6 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f9f4b03eaa2 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f9f4b1c4d12 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f9f4b1cc4ae in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f9f4b1cd4d2 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007f9f4b0852b6 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f9f4b1cfadb in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f9f4b042a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007f9f4b04c343 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f9f4a4d193a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007f9f4b04b457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f9f4b0a1ce4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f9f4b0a41ec in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f9f4b042a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f9f4b04c0f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007f9f4a4d193a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007f9f4a8ba7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007f9f4a8bc10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#41 0x00007f9f4a89635b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#42 0x00007f9f3429c32e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#43 0x00007f9f48df517d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007f9f48df5400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007f9f48df54a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007f9f4a529565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007f9f4a4d04db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007f9f4a4d8246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x00007f9f4f5ee28d in G4UIQt::SessionStart() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#50 0x000055a751e5450a in main (argc=1, argv=0x7ffcfb0e99b8) at /home/cde/mlrcd/remoll.cc:162
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f9f4f5eeab5 in G4UIQt::ReceiveG4cout(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#6  0x00007f9f4f0b3782 in G4coutDestination::ReceiveG4cout_(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4global.so
#7  0x00007f9f4f149651 in G4strstreambuf::sync() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#8  0x00007f9f4ef25a43 in std::ostream::flush() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f9f4eb566ff in G4GDMLRead::Read(G4String const&, bool, bool, bool) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4persistency.so
#10 0x00007f9f4ffa2090 in G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x55a75531ad20) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:35
#11 G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x55a75531ad20) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:31
#12 remollDetectorConstruction::ParseGDMLFile (this=0x55a75531abf0) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:544
#13 0x00007f9f4ffa2e85 in remollDetectorConstruction::Construct (this=0x55a75531abf0) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:912
#14 0x00007f9f4f1a853e in G4RunManager::InitializeGeometry() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#15 0x00007f9f4f1a82e4 in G4RunManager::Initialize() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#16 0x00007f9f4f1c620d in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#17 0x00007f9f4f12535f in G4UIcommand::DoIt(G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#18 0x00007f9f4f142c9a in G4UImanager::ApplyCommand(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#19 0x00007f9f4f5fd89f in G4VBasicShell::ExecuteCommand(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#20 0x00007f9f4f602ade in G4VBasicShell::ApplyShellCommand(G4String const&, bool&, bool&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#21 0x00007f9f4f5f5aa4 in G4UIQt::ButtonCallback(QString const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#22 0x00007f9f4a4fd458 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f9f4b03c3e6 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f9f4b03eaa2 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f9f4b1c4d12 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f9f4b1cc4ae in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f9f4b1cd4d2 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007f9f4b0852b6 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f9f4b1cfadb in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f9f4b042a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007f9f4b04c343 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f9f4a4d193a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007f9f4b04b457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f9f4b0a1ce4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f9f4b0a41ec in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f9f4b042a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f9f4b04c0f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007f9f4a4d193a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007f9f4a8ba7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007f9f4a8bc10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#41 0x00007f9f4a89635b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#42 0x00007f9f3429c32e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#43 0x00007f9f48df517d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007f9f48df5400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007f9f48df54a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007f9f4a529565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007f9f4a4d04db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007f9f4a4d8246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x00007f9f4f5ee28d in G4UIQt::SessionStart() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#50 0x000055a751e5450a in main (argc=1, argv=0x7ffcfb0e99b8) at /home/cde/mlrcd/remoll.cc:162
===========================================================
`

**Comment by wdconinc** [comment]
Can you send the hash of the version you're using? I'm pretty sure this has been fixed already. https://github.com/JeffersonLab/remoll/commit/e5272d08b9b9a40248a74c37880f9fcbffc0ac32

In particular, the defaults are not "schema validation off, overlap check off" as in your settings.

**Comment by rakithab** [comment]
This was related to version conflict in different required libraries.
