### ISSUE TITLE
Replace std::to_string (C++11 only) with backwards compatible solution

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#54]
Relevant line https://github.com/JeffersonLab/remoll/blob/306a6f616a158220a23dff43a3b5f5c1d6cf9e0e/src/remollGenericDetector.cc#L33

**Comment by wdconinc** [comment]
```std::stringstream ss;
ss << fDetNo;```
Then use `ss.str()` instead.

**Comment by cameronc137** [comment]
Commit 73bd1973255115fbe00fbeb3c1cfa4b8ffde33c7 fixes this problem and remoll successfully compiles on Centos 6.9.
