### ISSUE TITLE
Default beam energy of 11.0 GeV cannot be changed in macros or generators

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#58]
If I understand correctly, this default choice of the beam energy 
```
remollBeamTarget::remollBeamTarget()
 39 : fBeamEnergy(**gDefaultBeamE**),...............

```
(https://github.com/JeffersonLab/remoll/blob/cd7110a0842736747ef3e9c6f9da976392fdc63c/src/remollBeamTarget.cc#L39) to come from the global variable "const double gDefaultBeamE   = 11.0*GeV;"  in include/remollglobs.hh causes "/remoll/beamene NUMBER GeV" in macros (and in alternate generator source files that also rely on stuff like remollGenBeam's "double E = fBeamTarg->fBeamE;") to fail to change the beam energy.

This may be an issue of the messenger functions not being implemented properly, which I will now check, but regardless of the simplicity of the cause, the /remoll/beamene command is not functioning as advertised (or at least as included in the macros given in the master branch).

**Comment by cameronc137** [comment]
I see that between a version of the messenger I have from a year or so ago and a more recent change (https://github.com/JeffersonLab/remoll/blame/c45cfb32c6dd3587eb606973a41f9f8eeca0d0a3/src/remollBeamTarget.cc#L61) at #63dc350f34f95c87264d8e1e24e179fdb5459be0 that the messenger commands were moved over into the remollBeamTarget.cc file from the messenger file itself. 

Does this moved messenger system work? Am I just using the macro commands wrong?

**Comment by wdconinc** [comment]
Not sure I see the problem you're seeing with `/remoll/beamene`. I committed a6e5261503c1d64534e5aa4e0078c7358523f428 and it generates 4 root files with each the expected mean of `ev.p` (about half of beam energy).

**Comment by wdconinc** [comment]
(As an aside, with the change to geant4.10 and the associated multi-thread infrastructure, the past concept of using a single messenger class is not robust anymore. The event generators are per-thread, while the overall messenger is a single master-thread object. Setting the beam energy through the master thread would have required implementing logic to contact each daughter thread. By implementing the messenger at the per-thread level, that is not necessary and geant4 takes care of making sure that all daughter messengers are called.)

**Comment by cameronc137** [comment]
08bf76a7c791ebab18d7c832e158f7f924a0396c fixes this user-caused problem.

**Comment by wdconinc** [comment]
Possible fix in code to avoid this behavior is to instantiate remollBeamTarget in PrimaryGeneratorAction so it doesn't have to get deleted and re-instantiated on a generator change. Will test and see if that works.
