### ISSUE TITLE
Move handling of seed into a proper location

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#72]
Now in remoll Run and remoll Messenger. Should kill the global messenger.

**Comment by wdconinc** [comment]
Fixed in develop 71e4103..2320895

**Comment by wdconinc** [comment]
This hasn't been solved. remollRun is not created until start of first run, so /remoll/seed fails before then. Test case succeeds because the first of the test cases uses the default seed.

**Comment by cameronc137** [comment]
Is there another global or pre-"initialize" object that can hold the seed value while waiting for the run manager to instantiate?

**Comment by wdconinc** [comment]
Run action would be the next idea...

**Comment by wdconinc** [comment]
There's a difference however between preinit and the problem with remollrun. Preinit is only available in detector construction and physics list. But I think postinit idle is fine too. Run action is postinit. And I don't want to add anything preinit since I'm hoping to get rid of preinit entirely.

**Comment by wdconinc** [comment]
Fixed in 127b3a0a9e71b6a2c86174f0b5ee0fe9b2ff7624
