### ISSUE TITLE
Remove automatic emails to Moller mailing list for every commit, only send for merges into master

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#75]
Anecdotal reports of overwhelming number of emails... ;-)

Also, email sending functionality is being phased out  by GitHub. Alternative approach suggested by GitHub through Apps, but not clear how to implement that (yet).

Comments welcome, @cameronc137, @cipriangal . Should discuss in simulation meeting, @rakithab.

**Comment by cipriangal** [comment]
I am fine with the level of emails. They automatically get filtered and this way I don't have to visit the repo to see what is happening. I guess once GitHub removes this I will have to read through the moller_simulation_dev page to see what is happening.

**Comment by wdconinc** [comment]
There is also the internal github notification functionality and the slack channel.

**Comment by wdconinc** [comment]
I guess we'll keep the emails coming as long as the functionality is there...
