### ISSUE TITLE
Proposed branch deletion: bugfix-IOsegfaults

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#80]
@cameronc137 Is this still an issue? If not, could I suggest deletion of this branch? If it is, by all means keep the branch around! I am trying to reduce the number of branches before I split out geometry again. Each redundant branch here will cause a few more geometry branches if I'm to do this automatically.

**Comment by cameronc137** [comment]
It is fixed by the new branch structure and can be deleted. Thanks!

**Comment by wdconinc** [comment]
Deleted.
