### ISSUE TITLE
Proposed branch deletion: upstream_window

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#81]
This branch is fully included in v2.0.0 in master. I don't see a reason to keep it around. I think it got uploaded by someone doing forensics on yxzhao (@cipriangal ?). If there are uncommited changes from yxzhao on this branch that need to get merged in, let me know.

**Comment by cipriangal** [comment]
I pushed Yuxiang's changes a while back. There are not additional commits and if it has been integrated into master then we are safe to delete it.

**Comment by wdconinc** [comment]
Deleted branch upstream_window.
