### ISSUE TITLE
Threads hanging and double free() when sorting concurrently  

### ISSUE THREAD

**Issue by DanielDeLayo** [JeffersonLab/remoll#92]
When both threads are calling sort(), the threads either hang or (rarely) crash due to a double free()

https://github.com/JeffersonLab/remoll/blob/c26e88903d11fe49553a0f8f7bbae991a4f1c42c/include/remollGenericDetector.hh#L37

**Comment by wdconinc** [comment]
Yeah, and even a mutex doesn't solve this. I've pushed some changes just now, to the wrong branch. I'll try again to get them in develop :-) @cameronc137

**Comment by wdconinc** [comment]
Try again with the develop branch and let me know if the issue is still present.

**Comment by acfarrell** [comment]
This was happening on develop originally, but this fix works.
