### ISSUE TITLE
External generator segfaulting

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#93]
Remoll segfaults when reading input external generator data from a file

This happens for data generated from old remoll and v2 remoll. It is not clear if the branch is being set correctly in this class, and it may have changed with the new remollIO sub-branch structure as well, but I can't tell.

"G4WT1 > --> Event 0 starts with initial seeds (45410621,20657294).
G4WT0 > --> Event 2 starts with initial seeds (46822392,49845117).
G4WT1 > Could not find tree T in event file
G4WT1 > /home/audrey/remoll_jlab/remoll/src/remollVEventGen.cc line 132:  Event check failed for generator external.  Aborting
G4WT1 > Event 0x7fcce4527010 dump
G4WT1 >         -1e+09 nb effective cross section
G4WT1 >         -1e+15 ppm asymmetry
G4WT1 >         Q2 = -1e+09 GeV2
G4WT1 >         W2 = -1e+09 GeV2
G4WT1 >         th_com = -5.72958e+10 deg
G4WT1 >         0 particles generated
G4WT0 > Could not find tree T in event file
G4WT0 > /home/audrey/remoll_jlab/remoll/src/remollVEventGen.cc line 132:  Event check failed for generator external.  Aborting
G4WT0 > Event 0x7fccec5275f0 dump
G4WT0 >         -1e+09 nb effective cross section
G4WT0 >         -1e+15 ppm asymmetry
G4WT0 >         Q2 = -1e+09 GeV2
G4WT0 >         W2 = -1e+09 GeV2
G4WT0 >         th_com = -5.72958e+10 deg
G4WT0 >         0 particles generated
*** glibc detected *** ./remoll: double free or corruption (!prev): 0x0000000002c6bd50 ***
======= Backtrace: =========
"

https://github.com/JeffersonLab/remoll/blob/0746df8e02db62471f98478330546b6bda1bb210/src/remollGenExternal.cc#L59

**Comment by wdconinc** [comment]
Probably #62

**Comment by wdconinc** [comment]
Closing as this appears fixed. Please reopen if this is still an issue.
