### ISSUE TITLE
remollGenBeam ignores raster

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#95]
It would make more sense to include the raster in the beam generator. Currently the beam generator ignores raster in terms of position as well as direction.

**Comment by cameronc137** [comment]
In terms of making envelopes I think that including the raster is pretty important. What needs to be done to effect this? How is the raster being handled for the other generators?

**Comment by wdconinc** [comment]
Closed since implemented in develop (even if #180)
